In [1]:
a = [1,2,3,4,5]

In [2]:
a = [[1],[2],[3],[5]]

In [3]:
import numpy

In [4]:
import numpy as np #AS - Package an alias name np to be used in our code

In [5]:
arr = np.array([1,2,3])

In [12]:
arr.shape

(3,)

In [8]:
type(arr)

numpy.ndarray

In [9]:
#numpy - Numpy N-Dimensional Array!

In [10]:
arr_2d = np.array([[1,2,3],[5,6,7]])

In [11]:
arr_2d.shape

(2, 3)

In [13]:
arr_3d = np.array([[[1,2,3],[2,3,4],[4,5,6]],[[4,5,6],[7,8,9],[10,11,12]]])

In [14]:
arr_3d.shape

(2, 3, 3)

In [15]:
arr_sample = np.array(range(0,16))

In [17]:
arr_sample

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
arr_sample.shape

(16,)

In [20]:
arr_sample = arr_sample.reshape((4,4))

In [21]:
arr_sample.shape

(4, 4)

In [24]:
arr_sample

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
arr2 = arr_sample.T

In [26]:
arr_resultant = arr_sample+arr2

In [27]:
arr_resultant

array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [28]:
arr_resultant = arr_sample-arr2

In [29]:
arr_resultant

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [30]:
np.add(arr_sample,arr2)

array([[ 0,  5, 10, 15],
       [ 5, 10, 15, 20],
       [10, 15, 20, 25],
       [15, 20, 25, 30]])

In [32]:
np.subtract(arr_sample,arr2)

array([[ 0, -3, -6, -9],
       [ 3,  0, -3, -6],
       [ 6,  3,  0, -3],
       [ 9,  6,  3,  0]])

In [33]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a,b)

array([[4, 1],
       [2, 2]])

In [34]:
np.multiply(a,b)

array([[4, 0],
       [0, 2]])

In [49]:
np.nan

nan

In [42]:
np.concatenate([arr_sample,arr2],axis = 1)

array([[ 0,  1,  2,  3,  0,  4,  8, 12],
       [ 4,  5,  6,  7,  1,  5,  9, 13],
       [ 8,  9, 10, 11,  2,  6, 10, 14],
       [12, 13, 14, 15,  3,  7, 11, 15]])

In [43]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [45]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [47]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.sort([1,2,3,10,5])

array([ 1,  2,  3,  5, 10])