In [ ]:
#Agenda
1. Pytorch | Keras - Tensorflow
  a. Keras - Little customization missing
  b. Flexibility - more customizable
2. Tensor manipulation in Pytorch
3. Linear Regression with torch - NN - LR

In [1]:
import torch
print(torch.__version__)

2.2.1+cu121


In [ ]:
[] - List
{} - Set / Dict
() - Tuple
np - Arrays
torch - tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Scalar Specific function
scalar.item()

7

In [6]:
vector = torch.tensor([1,1])
vector

tensor([1, 1])

In [7]:
vector.ndim

1

In [8]:
MATRIX = torch.tensor([[7,8],[9,10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
torch.zeros(size = (3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
torch.ones(size = (3,4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [13]:
float_32_tensor = torch.tensor([3,4,6], dtype = None,device = None, requires_grad = False) #Device - CPU, GPU, TPU

In [14]:
float_32_tensor.dtype

torch.int64

In [15]:
float_32_tensor

tensor([3, 4, 6])

In [16]:
float_32_tensor = torch.tensor([3,4,6], dtype = torch.float32,device = None, requires_grad = False)

In [17]:
float_32_tensor.dtype

torch.float32

In [18]:
float_32_tensor

tensor([3., 4., 6.])

In [19]:
exampleTensor = torch.rand(3,4)

In [21]:
exampleTensor.shape

torch.Size([3, 4])

In [23]:
exampleTensor.dtype

torch.float32

In [24]:
exampleTensor.device

device(type='cpu')

In [25]:
float_32_tensor - 10

tensor([-7., -6., -4.])

In [26]:
tensor1 = torch.rand(3,3)
tensor2 = torch.rand(3,3)

In [27]:
tensor1 @ tensor2

tensor([[0.4623, 0.9814, 1.5291],
        [0.2614, 0.2135, 0.5770],
        [0.4016, 0.6192, 1.1049]])

In [28]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
x.min()

tensor(0)

In [30]:
x.max()

tensor(90)

In [31]:
x.sum()

tensor(450)

In [32]:
import torch
x = torch.arange(1.,8.)

In [34]:
x.shape

torch.Size([7])

In [35]:
x = x.reshape(1,7)

In [36]:
x.shape

torch.Size([1, 7])

In [38]:
x = x.squeeze()
x.shape

torch.Size([7])

In [40]:
x = x.unsqueeze(dim=0)
x.shape

torch.Size([1, 7])

In [2]:
import torch
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Changing runtime type to T4

In [4]:
!nvidia-smi

Sat Apr  6 03:59:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [5]:
import torch
torch.cuda.is_available()

True

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
torch.cuda.device_count()

1

In [9]:
#ONLY FOR MAC M1 - any apple silicons
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'cpu'

In [11]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [15]:
tensor_on_gpu = tensor.to(device)

In [16]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [17]:
tensor_on_gpu[0]

tensor(1, device='cuda:0')

In [18]:
tensor_on_gpu[0]*20

tensor(20, device='cuda:0')

In [19]:
tensor_on_gpu.cpu()

tensor([1, 2, 3])